<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="2" failed="1" ignored="0" total="3" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Covid19IndiaTestReport" duration-ms="64085" started-at="2020-04-15T07:05:54Z" finished-at="2020-04-15T07:06:59Z">
    <groups>
      <group name="regression">
        <method signature="CovidIndiaUITest.checkCaseCalculationsForAllStates()[pri:0, instance:com.ui.testautomation.CovidIndiaUITest@1e54cb33]" name="checkCaseCalculationsForAllStates" class="com.ui.testautomation.CovidIndiaUITest"/>
      </group> <!-- regression -->
      <group name="smoke">
        <method signature="CovidIndiaUITest.checkCaseCalculationsForAllStates()[pri:0, instance:com.ui.testautomation.CovidIndiaUITest@1e54cb33]" name="checkCaseCalculationsForAllStates" class="com.ui.testautomation.CovidIndiaUITest"/>
        <method signature="CovidIndiaUITest.checkCaseCalculationsForChandigarh()[pri:0, instance:com.ui.testautomation.CovidIndiaUITest@1e54cb33]" name="checkCaseCalculationsForChandigarh" class="com.ui.testautomation.CovidIndiaUITest"/>
      </group> <!-- smoke -->
      <group name="sanity">
        <method signature="CovidIndiaUITest.checkCaseCalculationsForDelhi()[pri:0, instance:com.ui.testautomation.CovidIndiaUITest@1e54cb33]" name="checkCaseCalculationsForDelhi" class="com.ui.testautomation.CovidIndiaUITest"/>
      </group> <!-- sanity -->
      <group name="failed">
        <method signature="CovidIndiaUITest.failedTest()[pri:0, instance:com.ui.testautomation.CovidIndiaUITest@1e54cb33]" name="failedTest" class="com.ui.testautomation.CovidIndiaUITest"/>
      </group> <!-- failed -->
    </groups>
    <test name="Test_Framework-Basic_Tests" duration-ms="64085" started-at="2020-04-15T07:05:54Z" finished-at="2020-04-15T07:06:59Z">
      <class name="com.ui.testautomation.CovidIndiaUITest">
        <test-method status="PASS" signature="initiateMethod(java.lang.reflect.Method)[pri:0, instance:com.ui.testautomation.CovidIndiaUITest@1e54cb33]" name="initiateMethod" is-config="true" duration-ms="1449" started-at="2020-04-15T12:35:54Z" finished-at="2020-04-15T12:35:56Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.ui.testautomation.CovidIndiaUITest.failedTest()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initiateMethod -->
        <test-method status="SKIP" signature="failedTest()[pri:0, instance:com.ui.testautomation.CovidIndiaUITest@1e54cb33]" name="failedTest" duration-ms="37" started-at="2020-04-15T12:35:56Z" description="Failed test" finished-at="2020-04-15T12:35:56Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Test failed]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Test failed
	at org.testng.Assert.fail(Assert.java:94)
	at com.ui.testautomation.CovidIndiaUITest.failedTest(CovidIndiaUITest.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:373)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:334)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:119)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:407)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failedTest -->
        <test-method status="PASS" signature="finish(java.lang.reflect.Method)[pri:0, instance:com.ui.testautomation.CovidIndiaUITest@1e54cb33]" name="finish" is-config="true" duration-ms="193" started-at="2020-04-15T12:36:09Z" finished-at="2020-04-15T12:36:09Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.ui.testautomation.CovidIndiaUITest.failedTest()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- finish -->
        <test-method status="PASS" signature="initiateMethod(java.lang.reflect.Method)[pri:0, instance:com.ui.testautomation.CovidIndiaUITest@1e54cb33]" name="initiateMethod" is-config="true" duration-ms="11668" started-at="2020-04-15T12:36:09Z" finished-at="2020-04-15T12:36:20Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.ui.testautomation.CovidIndiaUITest.failedTest()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initiateMethod -->
        <test-method status="SKIP" signature="failedTest()[pri:0, instance:com.ui.testautomation.CovidIndiaUITest@1e54cb33]" name="failedTest" duration-ms="4" started-at="2020-04-15T12:36:20Z" description="Failed test" finished-at="2020-04-15T12:36:20Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Test failed]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Test failed
	at org.testng.Assert.fail(Assert.java:94)
	at com.ui.testautomation.CovidIndiaUITest.failedTest(CovidIndiaUITest.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:998)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1200)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:373)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:334)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:119)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:407)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failedTest -->
        <test-method status="PASS" signature="finish(java.lang.reflect.Method)[pri:0, instance:com.ui.testautomation.CovidIndiaUITest@1e54cb33]" name="finish" is-config="true" duration-ms="97" started-at="2020-04-15T12:36:35Z" finished-at="2020-04-15T12:36:35Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.ui.testautomation.CovidIndiaUITest.failedTest()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- finish -->
        <test-method status="PASS" signature="initiateMethod(java.lang.reflect.Method)[pri:0, instance:com.ui.testautomation.CovidIndiaUITest@1e54cb33]" name="initiateMethod" is-config="true" duration-ms="11818" started-at="2020-04-15T12:36:35Z" finished-at="2020-04-15T12:36:47Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.ui.testautomation.CovidIndiaUITest.failedTest()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initiateMethod -->
        <test-method status="FAIL" signature="failedTest()[pri:0, instance:com.ui.testautomation.CovidIndiaUITest@1e54cb33]" name="failedTest" duration-ms="2" started-at="2020-04-15T12:36:47Z" description="Failed test" finished-at="2020-04-15T12:36:47Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Test failed]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Test failed
	at org.testng.Assert.fail(Assert.java:94)
	at com.ui.testautomation.CovidIndiaUITest.failedTest(CovidIndiaUITest.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:998)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1200)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:373)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:334)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:119)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:407)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failedTest -->
        <test-method status="PASS" signature="finish(java.lang.reflect.Method)[pri:0, instance:com.ui.testautomation.CovidIndiaUITest@1e54cb33]" name="finish" is-config="true" duration-ms="102" started-at="2020-04-15T12:36:58Z" finished-at="2020-04-15T12:36:58Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.ui.testautomation.CovidIndiaUITest.failedTest()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- finish -->
        <test-method status="PASS" signature="quit()[pri:0, instance:com.ui.testautomation.CovidIndiaUITest@1e54cb33]" name="quit" is-config="true" duration-ms="83" started-at="2020-04-15T12:36:58Z" finished-at="2020-04-15T12:36:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quit -->
      </class> <!-- com.ui.testautomation.CovidIndiaUITest -->
    </test> <!-- Test_Framework-Basic_Tests -->
  </suite> <!-- Covid19IndiaTestReport -->
</testng-results>
